steps:
  - name: 'gcr.io/$PROJECT_ID/scala-sbt'
    args: ['clean', 'test', 'docker:publishLocal']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'cards:1.0', 'eu.gcr.io/$PROJECT_ID/cards:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'eu.gcr.io/$PROJECT_ID/cards:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'cards:1.0', 'eu.gcr.io/$PROJECT_ID/cards']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'eu.gcr.io/$PROJECT_ID/cards']
